spring.application.name=Server

# MongoDB Configuration
spring.data.mongodb.uri=mongodb://localhost:27017/tsarburger
spring.data.mongodb.database=tsarburger

# JWT Configuration
jwt.secret=8Zz5tw0Ionm3XPZZfN0NOml3z9FMfmpgXwovR9fp6ryDIoGRM8EPHAB6iHsc0fb
jwt.expiration=86400000

# Server Configuration
server.port=8080
# server.servlet.context-path=/api

# Logging Configuration
logging.level.org.springframework=INFO
logging.level.org.example.server=DEBUG

# CORS Configuration
spring.web.cors.allowed-origins=http://localhost:3000
spring.web.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
spring.web.cors.allowed-headers=*
spring.web.cors.allow-credentials=true
